CREATE TABLE TB_CLIENTES2 
(
CPF VARCHAR2(11),
NOME VARCHAR2(100),
ENDERECO1 VARCHAR2(150),
ENDERECO2 VARCHAR2(150),
BAIRRO VARCHAR2(50),
CIDADE VARCHAR2(50),
ESTADO VARCHAR2(2),
CEP VARCHAR2(8),
DATA_NASCIMENTO DATE,
IDADE INTEGER,
SEXO VARCHAR2(1),
LIMITE_CREDITO NUMBER(15,2),
VOLUME_COMPRA NUMBER,
PRIMEIRA_COMPRA NUMBER(1)
);

CREATE TABLE TB_CLIENTES3 (
CPF VARCHAR2(11),
NOME VARCHAR2(100),
ENDERECO1 VARCHAR2(150),
ENDERECO2 VARCHAR2(150),
BAIRRO VARCHAR2(50),
CIDADE VARCHAR2(50),
ESTADO VARCHAR2(2),
CEP VARCHAR2(8),
DATA_NASCIMENTO DATE,
IDADE INTEGER,
SEXO VARCHAR2(1),
LIMITE_CREDITO NUMBER(15,2),
VOLUME_COMPRA NUMBER,
PRIMEIRA_COMPRA NUMBER(1)
);

DROP TABLE TB_CLIENTES3;

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00265','Jonh Wayne', TO_DATE('03/27/2019', 'MM/DD/YYYY'), 0.12
);

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00810','Marcia Almeida','14/12/2016', 0.18
);

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00414','Carlos Moreira','13/11/2015', 0.14
);

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00934','Juvenildo Martins','09/03/2010', 0.20
);

SELECT * FROM TB_VENDEDORES

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY (MATRICULA);

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00265','Jonh Wayne',TO_DATE('03/27/2019','MM/DD/YYYY'), 0.12
);

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00777','Katy Peterson',TO_DATE('02/04/2020','MM/DD/YYYY'), 0.10
);

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00342','Rodrigo Almeida','18/01/2022', 0.09
);

INSERT INTO TB_VENDEDORES (
     MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO
) VALUES (
     '00729','Patricia Martins','02/01/2022', 0.09
);

SELECT * FROM TB_VENDEDORES WHERE PERCENTUAL_COMISSAO < 0.17;

SELECT * FROM TB_VENDEDORES

SELECT * FROM TB_VENDEDORES WHERE DATA_ADMISSAO >= '31/12/2019';

SELECT * FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 9;

SELECT * FROM TB_VENDEDORES WHERE DATA_ADMISSAO >= '01/01/2020';

SELECT * FROM TB_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.19 OR PERCENTUAL_COMISSAO < 0.15; 




